export const names = [
  "John Doe",
  "Jane Smith",
  "Michael Johnson",
  "Emily Davis",
  "Chris Brown",
  "Sarah Wilson",
  "David Martinez",
  "Laura Garcia",
  "James Anderson",
  "Sophia Thomas",
  "Daniel Lee",
  "Olivia Taylor",
  "Matthew Harris",
  "Emma Clark",
  "Andrew Lewis",
  "Isabella Walker",
  "Joshua Hall",
  "Mia Allen",
  "Ethan Young",
  "Charlotte King",
];


export const positions = [
  "Software Engineer",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Data Scientist",
  "DevOps Engineer",
  "Mobile Developer",
  "Cloud Engineer",
  "Database Administrator",
  "Machine Learning Engineer",
  "Cybersecurity Analyst",
  "UI/UX Designer",
  "Technical Lead",
  "Product Manager",
  "QA Engineer",
  "IT Support Specialist",
  "System Administrator",
  "Network Engineer",
  "AI Researcher",
  "Blockchain Developer",
];

export const technologies = [
  "Python",
  "SQL",
  "Java",
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "MongoDB",
  "HTML",
  "CSS",
  "PHP",
  "Ruby",
  "C++",
  "C#",
  "Swift",
  "Go",
  "Kotlin",
  "Django",
  "Flask",
  "Spring",
  "Angular",
];